### ISSUE TITLE
Allow scrobbling to http-only listenbrainz servers

### ISSUE THREAD

**Issue by LeoVerto** [mariusor/mpris-scrobbler#36]
Currently scrobbling to a development listenbrainz server (as per  #33) fails with a "curl::error: SSL connect error" because mpris-scrobbler expects the endpoint to be HTTPS.

**Comment by mariusor** [comment]
Hey @LeoVerto, during the weekend I got cought up in a different project, so for the near future there likely won't be any work on this. Sorry.

**Comment by LeoVerto** [comment]
That's a shame to hear, guess I'll have to freshen up my C skills then.

**Comment by mariusor** [comment]
Hi again, @LeoVerto.

I made some changes in commit 37321511a. If you could compile the git version and give it a try I would appreciate it. You can now either edit your credentials file directly:

    [listenbrainz]
    enabled = true
    token = f91****-****-****-****-********518c
    url = http://localhost

Or use the command line `mpris-scrobbler-signon --url http://localhost:8080 token listenbrainz`

**Comment by xyank-github** [comment]
I'm using https://github.com/krateng/maloja to self-host a scrobbling service, and I tried this "fix", but mpris-scrobbler hasn't done anything so far.

Here's the system: cmus (with mpris support, verified using `playerctl`) runs music -> mpris-scrobbler -> maloja

I have verified maloja works using other scrobblers (using firefox, aka non mpris). This points to mpris-scrobbler being the issue here. Either it isn't running (it is running, I verified using `ps -ef | grep mpris`, which shows `/usr/local/bin/mpris-scrobbler -vv`).

here is my `credentials.txt`

```ini
[listenbrainz]
enabled = true
token = IFwwrl4[...... REDACTED....]kQJfxoSIf
url = http://localhost:42010/api/s/listenbrainz/1/submit-listens/
```

**Comment by mariusor** [comment]
Hi @xyank-github this looks like a completely different issue than what was reported here (ie, not being able to scrobble to http only listenbrainz services). Please open another issue.

However from a quick glance at your logs I don't think the problem is with the listenbrainz instance. The scrobbler doesn't seem to register that the track needs to be scrobbled, which indicates to me a problem with how cmus sends the track changed events.

If you open a new ticket, please include a longer log, maybe 2 or 3 listened songs, so I get to see all that the scrobbler loads. 

Thank you.
