### ISSUE TITLE
Add support for ListenBrainz

### ISSUE THREAD

**Issue by jflory7** [mariusor/mpris-scrobbler#5]
# Summary

Add support to submit listens to [ListenBrainz](https://listenbrainz.org/)

# Background

[ListenBrainz](https://listenbrainz.org/) is an open source project by the [MetaBrainz Foundation](https://metabrainz.org/) to replicate the basic functionality of the original Audioscrobbler®. You can read more about **[its goals and anti-goals](https://listenbrainz.org/goals)**.

# Details

The **[API documentation](https://listenbrainz.readthedocs.io/en/latest/index.html "ListenBrainz documentation")** is available on ReadTheDocs. More effort is going into the documentation to make it easy to understand and helpful to work with.

As a user, this is a feature that would make me excited, and I'd love to help promote the tool on the ListenBrainz site as a supported player, if possible!

On behalf of the ListenBrainz team, it would be awesome to see this tool support ListenBrainz. You are welcome to stop by `#metabrainz` IRC channel on Freenode and say hello. If you have questions or want to get in touch, you can find us in IRC or on our [Discourse](https://community.metabrainz.org/).

# Action

Please add support for submitting listens (with the MusicBrainz tags) to ListenBrainz.

Thanks for all of the work you are doing on this. If there's anything I can do to help, please feel free to ask! 😄

**Comment by mariusor** [comment]
Yes, I have this in mind already, and it's the next bigger thing I want to tackle. I didn't start it until now because somehow I was under the impression that the API is last.fm compatible and I was sure it was going to be a matter of hours. 

However it requires some changes that I need to explore a bit first. :)

**Comment by mariusor** [comment]
OK, first step is done: moving last.fm and libre.fm APIs from XML responses to json.

In the switch I removed the dependency for `libexpat` and replaced it with `json-c`.

Next step is to start a branch for listenbrainz and start developing the API. Probably this will require a better separation of the API related functions (libre.fm compatible vs. listenbrainz).

**Comment by jflory7** [comment]
@mariusor Can't wait! Thanks for your time working on this. If you have any questions, feel free to join us in `#metabrainz` on irc.freenode.net to ask! 😄

**Comment by mariusor** [comment]
OK, we have progress.

The scrobbler submits to listenbrainz correctly both the current playing and the just listened to track - using the code in the [listenbrainz branch](https://github.com/mariusor/mpris-scrobbler/tree/listenbrainz).

There are probably still a ton of memory leaks, as I didn't pay any mind to that, but at least it works without crashing.

The configuration/authentication needs to be done manually for now.

To enable it you need to add to `~/.config/mpris-scrobbler.ini` the following entry:

    [listenbrainz]
    enabled = true

Then edit manually the `~/.local/share/mpris-scrobbler/credentials` file with the **user token** from  your [listenbrainz profile page](https://listenbrainz.org/profile):

    [listenbrainz]
    user_name = <username>
    token = <token>

I haven't tested what happens if you update the credentials for lastfm or librefm after adding these entries, the file might get truncated or blow up your computer, so be careful and back-up.

In the next couple of days, most likely Friday or during the week-end, I want to do some code cleanups, update the documentation, pass it through coverity and tag a new release if everything goes OK.

**Comment by mariusor** [comment]
OK, I've finished the UX cleanup. The signon command supports manually adding the token, there's no need to edit the credentials file manually.

All changes reflected in the help command and in the [documentation](../#authenticate-to-the-service).

**Comment by jflory7** [comment]
@mariusor Amazing!!! This is so exciting to see. Thanks for your work on this. Once my exams finish up, I'll spend more time on the Fedora package and try to test out the new ListenBrainz implementation. :)
