### ISSUE TITLE
First track selected does not scrobble

### ISSUE THREAD

**Issue by alecvn** [mariusor/mpris-scrobbler#53]
OS:  Kubuntu 18.04 
Media Player: Google Music via MellowPlayer

Tracks that are selected don't scrobble at all, only tracks that follow-up naturally will be successfully scrobbled.

Eg. if I load up an album and select to start it at track 3, track 3 won't scrobble but tracks 4,5,6... do.

**Comment by mariusor** [comment]
Hi @alecvn, thank you for trying mpris-scrobbler. 

The first step would be to get some logs. Can you make sure you're running a debug build and run it from the command line with very vebose output and paste here the output:

```sh
$ mpris-scrobbler -vvv
```

My first suspicion is that MellowPlayer doesn't send the full MPRIS metadata struct when the track starts to play.

**Comment by mariusor** [comment]
Hey @alecvn I have released a new version of the scrobbler, could you check if it fixed your issue?

**Comment by xTpx** [comment]
Same problem with Arch AUR 2019-04-08 06:04. Doesn't seem to work for the patch.

**Comment by mariusor** [comment]
Hey @xTpx, please see my reply to alecvn and try to reproduce using verbose output. I can't do it myself as I don't have a Google music account.

**Comment by xTpx** [comment]
Thanks @mariusor 
But i use Audacious (Another issue maybe).
This is my part of journalctl -vvv 
https://textuploader.com/1dkz2

**Comment by mariusor** [comment]
@xTpx your log file doesn't contain enough information for me to make an informed opinion about the problem, but from what I can see the player didn't send the full track structure to DBUS when the play status changed. 

This usually happens when you pause/unpause, not when you play a song. If it happens when you start a song, it's definitely a bug in the Audacious mpris plugin and should be reported there.

However I have a long term plan on dealing with faulty mpris players. For the solution you can track issue #58.

**Comment by xTpx** [comment]
Thanks @mariusor  
I updated the log file, It might be useful (but I’m not sure).

**Comment by alecvn** [comment]
@mariusor, upgrading didn't seem to sort the problem out.

It doesn't seem like it's player specific since @xTpx is using Audacious.  I looked at the [log](https://pastebin.com/k2VmqZMn), from what I can tell the metadata sent with the first track is the same as the metadata sent with subsequent tracks.  The only difference is that the first track selected doesn't seem to register as a "change" in the scrobbler.
