### ISSUE TITLE
Scrobbling to ListenBrainz apparently lacks some data

### ISSUE THREAD

**Issue by alscaldas** [mariusor/mpris-scrobbler#78]
Hello there,

First off I'd like to congratulate you for this excellent piece of software. I installed it yesterday and it works nicely but for one little detail.

When I scrobble to ListenBrainz I notice that when using for example Lollypop (which has a sort of 'embedded scobbler') it generates clickable links both on the track and the artist (by the way all my audio files are correctly tagged). When I do the same using mpris-scrobbler it only generates a link on the track, but not on the artist, which probably means that it lacks some artist data, unique artist id or something of the kind to be sent (and that is sent correctly to the track).

I've attached a picture that shows what I mean. The entry that has no link was produced by a third scrobbler (that probably sends data lacking both on the track and the artist).

Any help would be much appreciated.

![Screenshot_20200704_111324](https://user-images.githubusercontent.com/29403156/86514385-50918d80-bde8-11ea-8e04-19866a72c904.png)

**Comment by mariusor** [comment]
Hey. The links are generated from the musicbrainz ids in the track's id3 tags.

To check if they are loaded you can start the scrobbler in a terminal with verbose output (`-vvv`) and use one of the songs that have the correct tags (`musicbrainz_trackid`, `musicbrainz_artistid`, `musicbrainz_albumid`) in the player you usually use. 

Then using a DBus viewer (I use `qdbusviewer-qt5`) search for `org.mpris.MediaPlayer2.{player_name}` and then expand the properties until you find `org.freedesktop.DBus.Properties` and connect to the signal `PropertiesChanged`. 

When you play the song from above you should see in the viewers output the data that the player sends to mpris-scrobbler. If that data contains the tags from above, then the bug is with the scrobbler, but in my experience not all players send the musicbrainz tags. The solution in this case would be to use one that does - (in my case, as you can see it's Rhythmbox)


![screenshot-20200704180232_525832123-swaygrab](https://user-images.githubusercontent.com/7553/86516475-21e3d900-be21-11ea-8643-8527921f01d6.png)

**Comment by alscaldas** [comment]
Thank you so much for your prompt reply.

Well, I begin to suspect that the trouble is indeed what you suggested... I tried 2 different players (in fact 3, but the third one was, I as said, Lollypop, which happens to have its own scrobbler). 

MPD (with its counterpart ncmpcpp) and Elisa (which is the kind of current 'default' KDE Plasma player). 

That's the output generated by ncmpcpp:

![Screenshot_20200704_150332](https://user-images.githubusercontent.com/29403156/86518346-a3c70880-be07-11ea-9394-6f8de4cc450f.png)

As you can see there's none of the 'Brainz' tags you referred to... which explains why it's not working properly and proves that the issue is with MPD, not with the scrobbler.

As for Elisa, I don't know exactly why it generates a lot of garbage on DBUS (or at least I think it's garbage as it's an output way different and more extense than the example you posted and the very outputs produced by my MPD) and each time I try to play a song it just crashes the scrobbler...

Here are the logs scrobbler logs:

```
[leonardocaldas@pequod ~]$ mpris-scrobbler -vvv
DEBUG   main::loading_credentials: ok
DEBUG   main::loading_config: ok
TRACING main::writing_pid: /run/user/1000/mpris-scrobbler.pid
TRACING dbus::add_match: type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/org/mpris/MediaPlayer2'
TRACING dbus::add_match: type='signal',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus'
TRACING events::add_event(0x55f15b643c90):add_watch
TRACING mpris_player::namespace[0]: org.mpris.MediaPlayer2.Lollypop :1.236
TRACING mpris_player::namespace[1]: org.mpris.MediaPlayer2.elisa :1.2717
TRACING mpris_player::namespace[2]: org.mpris.MediaPlayer2.kdeconnect.mpris_5aac16ca27864d63a955f633b338b7d7 :1.2660
TRACING mpris_player::namespace[3]: org.mpris.MediaPlayer2.mpd :1.24
ERROR     mpris::failed_to_load_player_name: This message iterator must have variant type
INFO    mpris_player::already_opened[1]: org.mpris.MediaPlayer2.elisa:1.2717
mpris-scrobbler: /mnt/Porqueras/Apps/Sources/git/mpris-scrobbler/build/../src/sdbus.h:1258: add_filter: Assertion `mpris_player_is_valid(player)' failed.
Abortado (imagem do núcleo gravada)
```

And here is Elisa DBUS content:

![Screenshot_20200704_151749](https://user-images.githubusercontent.com/29403156/86518715-ceb25c00-be09-11ea-9272-b61d3f433ba0.png)

I don't know why it crashes but it seems that it's not generating the expected tags anyway...

But that's ok. At least I could narrow things down and now I know that although the scrobbler is working correctly the issues are the players I'm using that aren't creating the necessary tags.

**Comment by mariusor** [comment]
You can open tickets with those players to add support for musicbrainz tags.

Personally I don't know of any Qt or KDE focused player that supports them. If you find one, please feel free to drop an update on this issue. :)

I'll go ahead and close this.
