### ISSUE TITLE
Scrobble without album

### ISSUE THREAD

**Issue by MinmoTech** [mariusor/mpris-scrobbler#95]
I usually listen to songs on youtube or songs downloaded from youtube with mpv.

For the first few tracks the scrobbling fails with the error `events::add_event:queue: skipping, track is invalid`.
It works again if I go backwards in the queue.
While I don't know why that makes it work again, the original error is caused by line 392 in `scrobble.h`: `strlen(m->album) > 0 &&`.

Because my music is downloaded from youtube often does not have an associated album.

Would it be a possibility to remove that requirement?

**Comment by mariusor** [comment]
Hello @MinmoTech, first of all apologies for the very late reply.

Due to the fact that Last.fm requires an album name in both the now playing and scrobble API calls, we can't remove this check. Even if we remove it, your songs would still not show up on last.fm due to the missing information. 

For the other services, maybe it's possible to remove the check, but I'm no longer actively working on this, and I would need confirmation form their API docs. 

A patch/pull-request (accompanied by links to the docs where listenbrainz/librefm say they accept API calls without albums) would be welcome though.

**Comment by DhruvaSambrani** [comment]
Listenbrainz does not require album to be sent in the payload (`release_name`) - https://listenbrainz.readthedocs.io/en/latest/users/json.html#payload-json-details

**Comment by MaxEtMoritz** [comment]
I don't know what the state of this issue currently is, but i built mpris-scrobbler from the current master branch and debugged why it would not submit a "playing now" to ListenBrainz for a YT video.
Running it with -vvv i discovered that it tried to submit it, but whatever payload was sent was rejected by the server.
The issue was that the album was submitted as an empty string. if it would be left out completely the request would have gone through without problems.

P.S. is there any other way to view detailed request and response info other than `nok` that setting up mitmproxy on my system?

**Comment by mariusor** [comment]
I'm not sure what's happening, if the length of the album is zero it should not be added to the payload, as you can see [here](https://github.com/mariusor/mpris-scrobbler/blob/master/src/listenbrainz_api.h#L194).

> is there any other way to view detailed request and response info

You can compile from source using the debug build type (`-Dbuildtype=debug` meson flag) and pass `-vvvv` to the binary, extra verbosity should be enabled.

Having said that, I checked and indeed the request looks like this: 

```
TRACING   request[POST]: https://api.listenbrainz.org/1/submit-listens
TRACING     request::body(0x591bcf0576b0:185): { "listen_type": "playing_now", "payload": [ { "track_metadata": { "release_name": "", "artist_name": "ZZZZZ", "track_name": "YYYYY (Remastered)" } } ] }
TRACING     request::headers[0]: Authorization: Token XXXXXXXX-YYYY-ZZZZ-ZZZZ-UUUUUU1cfe7c
TRACING     request::headers[1]: Content-Type: application/json
```

I'll look into it, but I have no idea when exactly. If you can find the problem and a way to fix it I'll gladly accept a PR.

**Comment by mariusor** [comment]
@MaxEtMoritz: done! Please check and let me know if it works for you.

**Comment by MaxEtMoritz** [comment]
@mariusor thank you for the fix. yes, the now playing is now correctly submitted.

**Comment by mariusor** [comment]
Cool. I'll tag a version later today.

I have to apologise to other people in the thread, @DhruvaSambrani and @MinmoTech for not having this fixed earlier as it was quite trivial. :bow:

**Comment by MaxEtMoritz** [comment]
@mariusor sorry, forgot to explicitly state that while the **now playing** does work now without album, the **scrobble** itself does not work, it is never tried.

the scrobble_is_valid function (and the print_scrobble_valid_check one too) misses the differentiation between LB and LastFM/LibreFM/etc.
https://github.com/mariusor/mpris-scrobbler/blob/65de0487680d7eb7b628fed614b3c9dcc5ff471a/src/scrobble.h#L375C9-L375C29 

i can try to make a PR, but i am not experienced in c++ programming (i can read the code, but writing is something different).

**Comment by mariusor** [comment]
That's a bit more complicated as the check for a valid submission is not done at submission time, therefore there's no way to do per service validation, and it uses the rules for last.fm, which include the album name existing.

**Comment by MaxEtMoritz** [comment]
Okay @mariusor. Can you re-open the issue then?

**Comment by mariusor** [comment]
Can you check again please. I refactored the validation for scrobbling to take into account where we submit.

**Comment by MaxEtMoritz** [comment]
Will check in about three days. I'm about to visit relatives now. Thank you for your effort.

**Comment by MaxEtMoritz** [comment]
@mariusor Checked today, everything works fine.
Thank You for Your effort!
