### ISSUE TITLE
Create whitelist and restrict scrobbling to only items in this list

### ISSUE THREAD

**Issue by gbcox** [mariusor/mpris-scrobbler#99]
I just noticed that mpris-scobbler is reporting everything from my system that has mpris enabled, Firefox in particular.  Which means when I listen to my voice messages, play youtube, etc. all these events are scrobbled.

Limiting scrobbles to those listed in a whitelist would prevent this from happening.

**Comment by mariusor** [comment]
Hey @gbcox... yet again I see the issue two months later. :) Sorry about that, and please use the mailing list. :P

There already is a way to filter out applications, you can find it documented in `man mpris-scrobber-config`. You just add lines like:

    ignore = ...

You can use either the player name, or the MPRIS bus name of the media player. Those can be found using QDBusViewer, the name is the value of the org.mpris.MediaPlayer2.Identity property and the bus name is the service name in the DBus list. (I am not sure if the bus name can be truncated, but I believe so, because when browsers expose media players in MPRIS they add a random string at the end, something like `org.mozilla.Firefox.deadbeef`, so you can add just `ignore = org.mozilla.Firefox`).

For firefox specifically, I usually disabled the MPRIS integration all together because it interferes with media keys usage.

**Comment by tibequadorian** [comment]
That's an ignorelist, is there a way to implement an allowlist?
